# Generated by Django 2.1.4 on 2019-01-07 14:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('courses', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=150, verbose_name='성')),
                ('first_name', models.CharField(max_length=30, verbose_name='이름')),
                ('type', models.CharField(choices=[('a', '지원자'), ('c', '채용연계기업'), ('s', '관리자')], default='s', max_length=1, verbose_name='타입')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='전화번호')),
                ('_company_name', models.CharField(blank=True, max_length=80, verbose_name='회사명')),
                ('_position', models.CharField(blank=True, max_length=50, verbose_name='직책')),
                ('is_published', models.BooleanField(default=False, verbose_name='이력서 공개여부')),
                ('is_looking', models.CharField(choices=[('n', '신입'), ('e', '경력'), ('s', '커리어 전환')], default='s', max_length=1, verbose_name='지원자 상태')),
                ('img_profile', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='user', verbose_name='프로필 이미지')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('short_intro', models.CharField(blank=True, max_length=200, verbose_name='한 줄 소개')),
                ('introduce', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='소개')),
                ('pdf1', models.FileField(blank=True, upload_to='users/pdf', verbose_name='PDF1')),
                ('pdf2', models.FileField(blank=True, upload_to='users/pdf', verbose_name='PDF2')),
                ('_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='administrator.Company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high', '매우능숙'), ('mid', '능숙'), ('low', '활용가능')], max_length=5, verbose_name='숙련도')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50, verbose_name='근무처')),
                ('responsibility', models.CharField(max_length=50, verbose_name='담당 업무')),
                ('position', models.CharField(max_length=30, verbose_name='직위')),
                ('start_date', models.DateField(verbose_name='시작일자')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
            options={
                'verbose_name': '경력',
                'verbose_name_plural': '경력 목록',
            },
        ),
        migrations.CreateModel(
            name='CompanyUserHireJobGroupWithApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait', '승인대기중'), ('approval', '승인완료')], default='wait', max_length=20, verbose_name='승인상태')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_job_group_set', related_query_name='hire_job_group', to=settings.AUTH_USER_MODEL, verbose_name='기업회원')),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_job_group_set', related_query_name='hire_job_group', to='courses.JobGroup', verbose_name='직군')),
            ],
            options={
                'verbose_name': '채용희망직군(상태포함)',
                'verbose_name_plural': '채용희망직군(상태포함) 목록',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='학교명')),
                ('major', models.CharField(blank=True, max_length=50, verbose_name='전공')),
                ('type', models.CharField(choices=[('grad', '졸업'), ('grad_ex', '졸업예정'), ('attend', '재학'), ('dropout', '중퇴')], max_length=12, verbose_name='상태')),
                ('start_date', models.DateField(verbose_name='시작일자')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
            options={
                'verbose_name': '교육과정',
                'verbose_name_plural': '교육과정 목록',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='자격증명')),
                ('organization', models.CharField(max_length=100, verbose_name='발급기관')),
                ('get_date', models.DateField(verbose_name='취득일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
            options={
                'verbose_name': '자격증',
                'verbose_name_plural': '자격증 목록',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='링크타입명')),
                ('img_icon', models.FileField(blank=True, upload_to='link', verbose_name='아이콘')),
            ],
            options={
                'verbose_name': '프로필 링크 아이템',
                'verbose_name_plural': '프로필 링크 아이템 목록',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='기술명')),
            ],
            options={
                'verbose_name': '보유기술',
                'verbose_name_plural': '보유기술 목록',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_userlike_set', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_userlike_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 찜',
                'verbose_name_plural': '사용자 찜 목록',
            },
        ),
        migrations.AddField(
            model_name='applicantskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.Skill'),
        ),
        migrations.AddField(
            model_name='applicantskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', related_query_name='skill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.Link'),
        ),
        migrations.AddField(
            model_name='applicantlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='_hire_job_groups',
            field=models.ManyToManyField(blank=True, related_name='hire_company_user_set', related_query_name='hire_company_user', through='members.CompanyUserHireJobGroupWithApprovalStatus', to='courses.JobGroup', verbose_name='채용희망직군'),
        ),
        migrations.AddField(
            model_name='user',
            name='_links',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', through='members.ApplicantLink', to='members.Link', verbose_name='링크 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='_skills',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', through='members.ApplicantSkill', to='members.Skill', verbose_name='보유 기술 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_groups',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='courses.JobGroup', verbose_name='취업희망 직군 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='followers', through='members.UserLike', to=settings.AUTH_USER_MODEL, verbose_name='즐겨찾기 한 유저 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ApplicantUser',
            fields=[
            ],
            options={
                'verbose_name': '지원자',
                'verbose_name_plural': '지원자 목록',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.user',),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
            ],
            options={
                'verbose_name': '기업회원',
                'verbose_name_plural': '기업회원 목록',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.user',),
        ),
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='companyuserhirejobgroupwithapprovalstatus',
            unique_together={('company_user', 'job_group')},
        ),
    ]
