# Generated by Django 2.1.3 on 2018-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('a', '지원자'), ('c', '참여기업')], default='s', max_length=1, verbose_name='타입'),
        ),
    ]
