# Generated by Django 2.1.7 on 2019-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuserhirejobgroupwithapprovalstatus',
            options={'verbose_name': '기업회원의 채용희망직군 관리자 승인', 'verbose_name_plural': '기업회원의 채용희망직군 관리자 승인 목록'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활성화 여부'),
        ),
    ]
