# Generated by Django 2.1.3 on 2018-11-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20181107_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '프로필 링크 아이템', 'verbose_name_plural': '프로필 링크 아이템 목록'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '보유기술', 'verbose_name_plural': '보유기술 목록'},
        ),
    ]
