# Generated by Django 2.1.3 on 2018-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20181116_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_looking',
            field=models.BooleanField(default=True, verbose_name='구직 여부'),
        ),
    ]
