# Generated by Django 2.1.3 on 2018-11-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
