# Generated by Django 2.1.3 on 2018-11-21 15:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20181116_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='소개'),
        ),
    ]
