# Generated by Django 2.1.3 on 2018-11-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20181122_0058'),
        ('members', '0009_auto_20181122_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='administrator.Company', verbose_name='회사'),
        ),
    ]
