# Generated by Django 2.1.3 on 2018-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181125_0259'),
        ('members', '0012_auto_20181124_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_groups',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='courses.JobGroup', verbose_name='취업희망 직군 목록'),
        ),
    ]
