# Generated by Django 2.1.3 on 2018-12-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181125_0259'),
        ('members', '0013_user_job_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUserHireJobGroupWithApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait', '승인대기중'), ('approval', '승인완료')], default='wait', max_length=20, verbose_name='승인상태')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_job_group_set', related_query_name='hire_job_group', to=settings.AUTH_USER_MODEL, verbose_name='기업회원')),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_job_group_set', related_query_name='hire_job_group', to='courses.JobGroup', verbose_name='직군')),
            ],
            options={
                'verbose_name': '채용직군 및 상태',
                'verbose_name_plural': '채용직군 및 상태 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='userlike',
            options={'verbose_name': '사용자 찜', 'verbose_name_plural': '사용자 찜 목록'},
        ),
        migrations.AddField(
            model_name='user',
            name='_hire_job_groups',
            field=models.ManyToManyField(blank=True, related_name='hire_company_user_set', related_query_name='hire_company_user', through='members.CompanyUserHireJobGroupWithApprovalStatus', to='courses.JobGroup', verbose_name='채용직군'),
        ),
        migrations.AlterUniqueTogether(
            name='companyuserhirejobgroupwithapprovalstatus',
            unique_together={('company_user', 'job_group')},
        ),
    ]
