# Generated by Django 2.1.4 on 2018-12-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_user_job_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='img_icon',
            field=models.FileField(blank=True, upload_to='link', verbose_name='아이콘'),
        ),
    ]
