# Generated by Django 2.1.4 on 2019-01-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20181227_2203'),
        ('members', '0014_auto_20181218_0249'),
    ]

    operations = [
    ]
