# Generated by Django 2.1.4 on 2019-01-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_merge_20190101_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf1',
            field=models.FileField(blank=True, upload_to='users/pdf', verbose_name='PDF1'),
        ),
        migrations.AddField(
            model_name='user',
            name='pdf2',
            field=models.FileField(blank=True, upload_to='users/pdf', verbose_name='PDF2'),
        ),
    ]
