# Generated by Django 2.1.3 on 2018-11-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='과정명')),
            ],
            options={
                'verbose_name': '과정',
                'verbose_name_plural': '과정 목록',
            },
        ),
        migrations.CreateModel(
            name='CoursePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='기수명')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='courses.Course', verbose_name='과정')),
            ],
            options={
                'verbose_name': '기수',
                'verbose_name_plural': '기수 목록',
            },
        ),
    ]
