# Generated by Django 2.1.4 on 2019-01-07 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='과정명')),
            ],
            options={
                'verbose_name': '과정',
                'verbose_name_plural': '과정 목록',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CoursePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='기수명')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='courses.Course', verbose_name='과정')),
            ],
            options={
                'verbose_name': '과정 기수',
                'verbose_name_plural': '과정 기수 목록',
                'ordering': ['course__title', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='분야명')),
            ],
            options={
                'verbose_name': '분야',
                'verbose_name_plural': '분야 목록',
            },
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='직군명')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='courses.JobCategory', verbose_name='분야')),
            ],
            options={
                'verbose_name': '직군',
                'verbose_name_plural': '직군 목록',
                'ordering': ('category__title', 'title'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='courses.JobGroup', verbose_name='직군'),
        ),
    ]
