# Generated by Django 2.1.3 on 2018-11-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': '과정', 'verbose_name_plural': '과정 목록'},
        ),
        migrations.AlterModelOptions(
            name='courseperiod',
            options={'ordering': ['course__title', 'title'], 'verbose_name': '과정 기수', 'verbose_name_plural': '과정 기수 목록'},
        ),
    ]
