# Generated by Django 2.1.3 on 2018-11-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181112_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='분야명')),
            ],
            options={
                'verbose_name': '분야',
                'verbose_name_plural': '분야 목록',
            },
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='직군명')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='courses.JobCategory', verbose_name='분야')),
            ],
            options={
                'verbose_name': '직군',
                'verbose_name_plural': '직군 목록',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='courses.JobGroup', verbose_name='직군'),
            preserve_default=False,
        ),
    ]
