# Generated by Django 2.1.3 on 2018-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181125_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobgroup',
            options={'ordering': ('category__title', 'title'), 'verbose_name': '직군', 'verbose_name_plural': '직군 목록'},
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='분야명'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='직군명'),
        ),
    ]
