# Generated by Django 2.1.4 on 2019-01-07 14:47

import ckeditor.fields
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('s', '스타트업'), ('a', '에이전시'), ('n', '일반기업')], max_length=1, verbose_name='기업 종류')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='회사명')),
                ('img_logo', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='company', verbose_name='로고')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('is_show', models.BooleanField(default=False, verbose_name='채용연계기업 목록에 표시')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='서비스명')),
            ],
            options={
                'verbose_name': '기업 서비스 분류',
                'verbose_name_plural': '기업 서비스 분류 목록',
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_image', models.ImageField(blank=True, upload_to='index', verbose_name='메인페이지 이미지')),
                ('index_color', colorful.fields.RGBColorField(blank=True, help_text='배너 이미지의 남는 공간을 채울 배경색입니다.', verbose_name='메인페이지 배경색')),
                ('index_height', models.IntegerField(default=200, help_text='메인 배너 이미지의 세로 길이를 지정합니다. 가로길이는 세로 길이의 비율로 정해집니다.', verbose_name='메인페이지 이미지 세로 길이(px)')),
                ('index_mobile_image', models.ImageField(blank=True, help_text='모바일 이미지는 세로길이와 관계없이 가로를 가득 채우도록 설정됩니다', upload_to='index', verbose_name='메인페이지 모바일 이미지')),
                ('index_mobile_color', colorful.fields.RGBColorField(blank=True, verbose_name='메인페이지 모바일 배경색')),
                ('index_mobile_height', models.IntegerField(default=240, help_text='모바일 메인 배너 이미지의 세로 길이를 지정합니다. 가로길이는 세로길이와 관계없이 가로를 가득 채우도록 설정됩니다', verbose_name='메인페이지 모바일 이미지 세로 길이(px)')),
                ('company_list_image', models.ImageField(blank=True, help_text='채용연계기업 목록의 배너 이미지 입니다.', upload_to='static', verbose_name='채용연계기업 목록 이미지')),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, verbose_name='개인정보 취급방침')),
                ('terms_of_service', ckeditor.fields.RichTextField(blank=True, verbose_name='이용약관')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정적 콘텐츠',
                'verbose_name_plural': '정적 콘텐츠 목록',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Service', verbose_name='서비스 종류'),
        ),
    ]
