# Generated by Django 2.1.3 on 2018-11-21 15:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, verbose_name='개인정보 취급방침')),
                ('terms_of_service', ckeditor.fields.RichTextField(blank=True, verbose_name='이용약관')),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
