# Generated by Django 2.1.3 on 2018-11-21 15:58

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='회사명')),
                ('img_logo', models.ImageField(blank=True, upload_to='company', verbose_name='로고')),
                ('is_show', models.BooleanField(default=False, verbose_name='참여기업 목록에 표시')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='staticcontent',
            options={'verbose_name': '정적 콘텐츠', 'verbose_name_plural': '정적 콘텐츠 목록'},
        ),
        migrations.RenameField(
            model_name='staticcontent',
            old_name='modified_at',
            new_name='modified',
        ),
    ]
