# Generated by Django 2.1.5 on 2019-01-20 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='index_html',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='메인 HTML'),
        ),
    ]
