# Generated by Django 2.1.3 on 2018-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20181122_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': '회사', 'verbose_name_plural': '회사 목록'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='회사명'),
        ),
    ]
