# Generated by Django 2.1.5 on 2019-01-21 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0003_staticcontent_index_mobile_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_applied', models.BooleanField(default=False, verbose_name='적용여부')),
                ('users', models.ManyToManyField(blank=True, related_name='mail_group_set', related_query_name='mail_group', to=settings.AUTH_USER_MODEL, verbose_name='구성원')),
            ],
            options={
                'verbose_name': '메일링 그룹',
                'verbose_name_plural': '메일링 그룹 목록',
            },
        ),
    ]
