# Generated by Django 2.1.3 on 2018-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20181122_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='index_height',
            field=models.IntegerField(default=200, verbose_name='메인페이지 높이(px)'),
        ),
    ]
