# Generated by Django 2.1.5 on 2019-01-21 10:46

from django.db import migrations

from ..models import MailingGroup


def forwards_func(apps, schema_editor):
    MailingGroup.objects.create_initial()


def reverse_func(apps, schema_editor):
    MailingGroup = apps.get_model('administrator', 'MailingGroup')
    db_alias = schema_editor.connection.alias
    MailingGroup.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0004_mailinggroup'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
