# Generated by Django 2.1.7 on 2019-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_create_initial_mailinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinggroup',
            name='code',
            field=models.CharField(choices=[('company_user_jobgroup_approve', '기업회원의 채용희망직군 승인'), ('user_joined', '사용자 회원가입'), ('send_hire_mail', '기업이 지원자에게 메일 발송')], max_length=50, verbose_name='코드'),
        ),
    ]
