# Generated by Django 2.1.3 on 2018-11-28 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_staticcontent_index_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='서비스명')),
            ],
            options={
                'verbose_name': '기업 서비스 분류',
                'verbose_name_plural': '기업 서비스 분류 목록',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('s', '스타트업'), ('a', '에이전시'), ('n', '일반기업')], default='n', max_length=1, verbose_name='기업 종류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Service', verbose_name='서비스 종류'),
        ),
    ]
