# Generated by Django 2.1.7 on 2019-04-12 08:51

from django.db import migrations


def forward_func(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    db_alias = schema_editor.connection.alias
    Site.objects.using(db_alias).update_or_create(
        pk=1,
        defaults={
            'domain': 'link.fastcampus.co.kr',
            'name': 'link.fastcampus.co.kr',
        }
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0006_auto_20190223_1805'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
