# Generated by Django 2.1.3 on 2018-11-28 23:30

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20181129_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='company_list_image',
            field=models.ImageField(blank=True, upload_to='static', verbose_name='참여기업 목록 이미지'),
        ),
        migrations.AlterField(
            model_name='company',
            name='img_logo',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='company', verbose_name='로고'),
        ),
    ]
