# Generated by Django 2.1.3 on 2018-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='index_mobile_height',
            field=models.IntegerField(default=240, help_text='모바일 메인 배너 이미지의 세로 길이를 지정합니다. 가로길이는 세로길이와 관계없이 가로를 가득 채우도록 설정됩니다', verbose_name='메인페이지 모바일 이미지 세로 길이(px)'),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='index_mobile_image',
            field=models.ImageField(blank=True, help_text='모바일 이미지는 세로길이와 관계없이 가로를 가득 채우도록 설정됩니다', upload_to='index', verbose_name='메인페이지 모바일 이미지'),
        ),
    ]
