"""
Django settings for FastCampus project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from djs import import_secrets

from ..jinja2 import environment

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROOT_DIR = os.path.dirname(BASE_DIR)
SECRETS_DIR = os.path.join(ROOT_DIR, '.secrets')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

PRINT_JSON_SETTINGS = False
import_secrets()

# Essential
SITE_ID = 1

# Static
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    STATIC_DIR,
]
MEDIA_ROOT = os.path.join(ROOT_DIR, '.media')
STATIC_ROOT = os.path.join(ROOT_DIR, '.static')

# django-sass-processor, django-compressor
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]
COMPRESS_JINJA2_GET_ENVIRONMENT = environment

# AWS
AWS_AUTO_CREATE_BUCKET = True
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_REGION_NAME = 'ap-northeast-2'
AWS_DEFAULT_ACL = None

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

# Auth
AUTH_USER_MODEL = 'members.User'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'members.backends.SettingsBackend',
]

# django-phonenumber-field
PHONENUMBER_DEFAULT_REGION = 'KR'
PHONENUMBER_DB_FORMAT = 'NATIONAL'

# Date/Time Format
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d'

# django-modeladmin-reorder
ADMIN_REORDER = (
    'sites',
    'contenttypes',
    {'app': 'auth', 'label': '인증, 권한', 'models': (
        {
            'model': 'auth.Permission',
            'label': '권한',
        },
        {
            'model': 'auth.Group',
            'label': '권한 그룹',
        },
    )},
    {'app': 'administrator', 'label': '회사(채용연계기업) 관리', 'models': (
        'administrator.Service',
        'administrator.Company',
    )},
    {'app': 'administrator', 'label': '기타 관리자 콘텐츠 관리', 'models': (
        'members.User',
        'administrator.StaticContent',
    )},
    {'app': 'members', 'label': '기업회원 관리', 'models': (
        'members.CompanyUser',
        'members.CompanyUserHireJobGroupWithApprovalStatus',
    )},
    {'app': 'members', 'label': '지원자 관리', 'models': (
        'members.ApplicantUser',
    )},
    {'app': 'members', 'label': '이력서 항목 관리', 'models': (
        'members.Link',
        'members.Skill',
    )},
    {'app': 'courses', 'label': '과정 관리', 'models': (
        'courses.JobCategory',
        'courses.JobGroup',
        'courses.Course',
        'courses.CoursePeriod',
    )},
)

# ckeditor
CKEDITOR_UPLOAD_PATH = 'ckeditor/'
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Default',
        'toolbar_Default': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
        ],
    },
}

# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

ALLOWED_HOSTS = []
INSTALLED_APPS = [
    'administrator.apps.AdministratorConfig',
    'courses.apps.CoursesConfig',
    'members.apps.MembersConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'admin_reorder',
    'ckeditor',
    'ckeditor_uploader',
    # Admin ColorPicker
    'colorful',
    'django_extensions',
    'django_fields',
    'phonenumber_field',
    'rest_framework',
    'sass_processor',
    'storages',
]

# SettingsBackend
DEFAULT_USERS = {
    'default_applicant@lhy.kr': {
        'email': '',
        'password': 'pbkdf2_sha256$120000$6bRc6EXjatPi$KjmUANv30sG+5rJBeozHndl2EEw2aLGoCdpkpDSRArk=',
        'last_name': '아메리카노',
        'first_name': '그란데',
        'type': 'a',
        'phone_number': '010-1234-1234',
        'birth_date': '1990-01-01',
    },
    'default_company@lhy.kr': {
        'password': 'pbkdf2_sha256$120000$6bRc6EXjatPi$KjmUANv30sG+5rJBeozHndl2EEw2aLGoCdpkpDSRArk=',
        'last_name': '카라멜마끼아또',
        'first_name': '벤티',
        'type': 'c',
        'phone_number': '010-1235-1235',
        'birth_date': '1980-01-01',
    },
    'dev@lhy.kr': {
        'password': 'pbkdf2_sha256$120000$6bRc6EXjatPi$KjmUANv30sG+5rJBeozHndl2EEw2aLGoCdpkpDSRArk=',
        'last_name': '이',
        'first_name': '한영',
        'type': 's',
        'phone_number': '010-4432-1234',
        'birth_date': '1988-03-24',
        'is_staff': True,
        'is_superuser': True,
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            TEMPLATES_DIR,
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            'environment': 'config.jinja2.environment',
            'context_processors': [
                'courses.context_processors.job',
            ]
        },
    },
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_L10N = True
USE_TZ = True
